### ISSUE TITLE
Parsing bug in Dynamic C 10.72C compiler

### ISSUE THREAD

**Issue by ghost** [digidotcom/DCRabbit_10#15]
I’m trying to compile code using the Dynamic C 10.72C IDE, but I get the following error message:

>  Duplicate 'const' keywords not allowed in this context.

The following is the test code which triggers the error – a simple function with two `const` parameters:

```C
int foo(const int* bar, const int* qaz){
    int c;

    c = (*bar) * (*qaz);

    return c;
}

int main(){
    int d;
    const int b = 3;
    const int q = 4;

    d = foo(&b,&q);
    printf ("%d", d);

    return 0;
}
```

I suspect this is a parsing bug since the error message only appears when there are multiple `const` keyword qualifiers before the closing parentheses; it goes away when there is only one.

**Comment by tomlogic** [comment]
You are correct that this is a parsing bug with the compiler, and is listed as a known issue in the [README.txt](https://github.com/digidotcom/DCRabbit_10/blob/master/README.TXT#L918) file.

```
28. The compiler incorrectly throws an error ("Duplicate 'const' keywords not
    allowed in this context.") if a function contains multiple, non-pointer
    `const` parameters.

    Work-around example: replace

        void foo(const int bar, const int baz) {}

    with

        typedef const int const_int;
        void foo(const_int bar, const_int baz) {}
```
As of now, Digi is providing updates to libraries and sample code, but is not making updates to the compiler itself.  Since it is a "known issue", it should be addressed if/when Digi releases an updated compiler.
